#!/bin/bash

# Uptime Kuma Setup Instructions
# Prints guidance for configuring Uptime Kuma after deployment

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}=========================================${NC}"
echo -e "${BLUE}   Uptime Kuma Setup${NC}"
echo -e "${BLUE}=========================================${NC}"
echo ""
echo -e "${YELLOW}Step 1: Initial Setup${NC}"
echo "  Open http://localhost:3001 (or via SSH tunnel) and create an admin account."
echo "  SSH tunnel: ssh -L 3001:127.0.0.1:3001 user@your-server"
echo ""
echo -e "${YELLOW}Step 2: Add Monitors${NC}"
echo "  Recommended monitors to add:"
echo ""
echo "  Nextcloud:"
echo "    - Type: HTTP(s)"
echo "    - URL: http://nextcloud-app/status.php"
echo "    - Expected keyword: \"installed\":true"
echo ""
echo "  MariaDB:"
echo "    - Type: Docker Container"
echo "    - Container: nextcloud-db"
echo ""
echo "  Redis:"
echo "    - Type: Docker Container"
echo "    - Container: nextcloud-redis"
echo ""
echo "  ClamAV:"
echo "    - Type: Docker Container"
echo "    - Container: nextcloud-clamav"
echo ""
echo "  Ente Photos:"
echo "    - Type: HTTP(s)"
echo "    - URL: http://ente-web:3000"
echo "    - Name: Ente Web"
echo ""
echo "  Ente API:"
echo "    - Type: HTTP(s)"
echo "    - URL: http://ente-museum:8080/ping"
echo "    - Name: Ente API"
echo ""
echo "  Ente Postgres:"
echo "    - Type: Docker Container"
echo "    - Container: ente-postgres"
echo ""
echo -e "${YELLOW}Step 3: Status Page${NC}"
echo "  Create a status page in Kuma's UI to display service health."
echo "  The status page API is available at: http://localhost:3001/api/status-page/heartbeat/<slug>"
echo ""
echo -e "${YELLOW}Step 4: External Access (Optional)${NC}"
echo "  To expose Kuma externally, add a Nginx proxy pass. For example:"
echo ""
echo "  # In your Nginx config, add a new server block or location:"
echo "  server {"
echo "      server_name status.thonbecker.biz;"
echo "      location / {"
echo "          proxy_pass http://127.0.0.1:3001/;"
echo "          proxy_set_header Host \$host;"
echo "          proxy_set_header X-Real-IP \$remote_addr;"
echo "          proxy_http_version 1.1;"
echo "          proxy_set_header Upgrade \$http_upgrade;"
echo "          proxy_set_header Connection \"upgrade\";"
echo "      }"
echo "  }"
echo ""
echo -e "${GREEN}Kuma is running at http://127.0.0.1:3001${NC}"
